### PR TITLE
Fix generator. Do not remove jQuery plugins from application.js

### LINKED ISSUE #117: Generator breaks jQuery plugins requires at application.js
```
//= require jquery-ui.min
//= require jquery.fileupload
```
becomes
```
-ui.min
.fileupload
```

### PR DESCRIPTION
**Pull request by szyablitsky**
Fixes #117.

### CODE REVIEW

File: lib/generators/react_on_rails/base_generator.rb [hunk 1]
```diff
@@ -86,7 +86,7 @@ def update_application_js
       def strip_application_js_of_incompatible_sprockets_statements
         application_js = File.join(destination_root, "app/assets/javascripts/application.js")
         gsub_file(application_js, "//= require jquery_ujs", "")
-        gsub_file(application_js, "//= require jquery", "")
+        gsub_file(application_js, /\/\/= require jquery$/, "")
```
Comment (justin808) [inline lib/generators/react_on_rails/base_generator.rb]: :+1:

File: spec/react_on_rails/support/generator_spec_helper.rb [hunk 2]
```diff
@@ -17,6 +17,7 @@ def run_generator_test_with_args(args, options = {})
     app_js_data = <<-DATA.strip_heredoc
       //= require jquery
       //= require jquery_ujs
+      //= require jquery-ui
```
Comment (justin808) [inline spec/react_on_rails/support/generator_spec_helper.rb:20]: Nice. This verifies we don't mess with this one.

**Comment by justin808** [comment]
:clap: :clap: :+1: 

This looks great! Once the CI passe, I'm merging. 

Thanks @szyablitsky!
