### PR TITLE
Fix bug in error messages printing

### LINKED ISSUE #36: In the error message handling, we print SERVER_SIDE instead of CLIENT_SIDE
This code in: https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/react_renderer.rb#L103

needs to take an option so what we use on the server and client side is different.

We're printing server side for client side messages!
```
console.error('SERVER SIDE: Exception in server side rendering!');
      if (e.fileName) {
        console.error('SERVER SIDE: location: ' + e.fileName + ':' + e.lineNumber);
      }
      console.error('SERVER SIDE: message: ' + e.message);
      console.error('SERVER SIDE: stack: ' + e.stack);
      msg += 'SERVER SIDE Exception in rendering!\\n' +
        (e.fileName ? '\\nlocation: ' + e.fileName + ':' + e.lineNumber : '') +
        '\\nMessage: ' + e.message + '\\n\\n' + e.stack;
```

### PR DESCRIPTION
**Pull request by josiasds**
This should fix #36.

@justin808 Can you review it?

### CODE REVIEW

File: app/helpers/react_on_rails_helper.rb [hunk 1]
```diff
@@ -89,12 +89,11 @@ def server_rendered_react_component_html(options, props, react_component_name)
...
       options[:react_component_name] = react_component_name
-      server_rendered_react_component_html =
-        render_js(render_js_expression, options)
+      options[:prerender] = true
+      render_js(render_js_expression, options)
     else
-      server_rendered_react_component_html = ""
+      ''
     end
-    server_rendered_react_component_html
```
Comment (justin808) [inline app/helpers/react_on_rails_helper.rb:97]: :+1:

File: lib/react_on_rails/react_renderer.rb [hunk 2]
```diff
@@ -70,7 +71,7 @@ def render_js(js_code, options = {})
       end
     end
 
-    def self.wrap_code_with_exception_handler(js_code, component_name)
+    def self.wrap_code_with_exception_handler(js_code, component_name, prerender)
```
Comment (justin808) [inline lib/react_on_rails/react_renderer.rb]: Let's not use the variable name `prerender` as that's confusing because what's really important is whether or not the code is running server side.

So how about `server_side`? True means running on server. False means running in client.

File: lib/react_on_rails/react_renderer.rb [hunk 3]
```diff
@@ -100,24 +101,31 @@ def self.wrap_code_with_exception_handler(js_code, component_name)
...
 
-      console.error('SERVER SIDE: Exception in server side rendering!');
+      #{render_error_messages(prerender)}
+    }
+      JS
+    end
+
+    private
+
+    def self.render_error_messages(prerender)
```
Comment (justin808) [inline lib/react_on_rails/react_renderer.rb]: `server_side` rather than `prerender`

File: lib/react_on_rails/react_renderer.rb [hunk 4]
```diff
@@ -100,24 +101,31 @@ def self.wrap_code_with_exception_handler(js_code, component_name)
...
+      side = prerender ? 'SERVER' : 'CLIENT'
```
Comment (justin808) [inline lib/react_on_rails/react_renderer.rb]: `server_or_client` rather than `side`

File: lib/react_on_rails/react_renderer.rb [hunk 5]
```diff
@@ -100,24 +101,31 @@ def self.wrap_code_with_exception_handler(js_code, component_name)
...
         (e.fileName ? '\\nlocation: ' + e.fileName + ':' + e.lineNumber : '') +
         '\\nMessage: ' + e.message + '\\n\\n' + e.stack;
 
       var reactElement = React.createElement('pre', null, msg);
       result = React.renderToString(reactElement);
-    }
       JS
     end
 
-    private
```
Comment (justin808) [inline lib/react_on_rails/react_renderer.rb:119]: why remove private?

Comment (josiasds) [inline lib/react_on_rails/react_renderer.rb:119]: it wasn't removed, it's in the line 109

**Comment by josiasds** [comment]
@justin808 Done!

**Comment by justin808** [comment]
I changed the strategy so that the place we put in the location of the messages is inside of the place where we polyfill on the server.
